
project:
  type: website

website:
  title: "Quarto tutorial"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: Home
      - text: Lessons
        menu:
          - href: doc/lesson/lesson1.qmd
            text: "Lesson 1"
          - href: doc/lesson/lesson2.qmd
            text: "Lesson 2"
      - text: Presentation
        menu:
          - href: doc/presentation/presentation1.qmd
            text: "Presentation 1"
      - text: Practicals
        menu:
          - href: doc/practical/practical1.qmd
            text: "Practical 1"
    right:
      - href: doc/getting-started.qmd
        text: Getting started
      - text: Examples
        menu:
          - href: doc/examples/lesson.qmd
            text: "Lesson"
          - href: doc/examples/notebook.qmd
            text: "Notebook"
          - href: doc/examples/practical.qmd
            text: "Practical"
          - href: doc/examples/presentation.qmd
            text: "Presentation"
          - href: doc/examples/python.qmd
            text: "Python"
          - href: doc/examples/R.qmd
            text: "R"
      - icon: github
        href: https://github.com/ludo2ne/quarto-tuto
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Code source](https://github.com/ludo2ne/Quarto-tuto){.external target="_blank"}
  repo-url: https://github.com/ludo2ne/quarto-tuto
  repo-branch: main
  reader-mode: true

format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
