
project:
  type: website

website:
  title: "Quarto tuto"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: Home
      - href: doc/create-website.qmd
        text: Getting started
      - text: Lessons
        menu:
          - href: doc/lesson/lesson1.qmd
            text: "Lesson 1"
          - href: doc/lesson/lesson2.qmd
            text: "Lesson 2"
      - text: Slides
        menu:
          - href: doc/slide/slide1.qmd
            text: "Slides n°1"
      - text: Practicals
        menu:
          - href: doc/practical/practical1.qmd
            text: "Practical 1"
    right:
      - text: Examples
        menu:
          - href: doc/examples/lesson.qmd
            text: "Lesson"
          - href: doc/examples/slide.qmd
            text: "Slides"
          - href: doc/examples/codeR.qmd
            text: "Slides R"
          - href: doc/examples/codePython.qmd
            text: "Slides Python"
      - icon: github
        href: https://github.com/ludo2ne/quarto-tuto
        target: "_blank"
  page-footer:
    right: |
      Website built with <a href=https://quarto.org/ target="_blank">Quarto</a><br>
      <a href=https://github.com/ludo2ne/quarto-tuto target="_blank">Source code</a>
  repo-url: https://github.com/ludo2ne/quarto-tuto
  repo-branch: main
  reader-mode: true

format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
