var:
  url-repo: https://github.com/ludo2ne/Quarto-tuto   # to call this value : {{< meta var.url-repo >}}

project:
  type: website

website:
  title: "Quarto tutorial"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  reader-mode: true
  navbar:
    background: "#447099"
    left:
      - icon: house
        href: index.qmd
        text: Home
      - href: doc/getting-started.qmd
        text: Getting started
      - text: Examples
        menu:
          - href: doc/examples/lesson.qmd
            text: "Lesson"
          - href: doc/examples/notebook.qmd
            text: "Jupyter Notebook"
          - href: doc/examples/practical.qmd
            text: "Practical"
          - href: doc/examples/presentation.qmd
            text: "Presentation"
          - href: doc/examples/python.qmd
            text: "Python"
          - href: doc/examples/R.qmd
            text: "R"
      - href: doc/resources.qmd
        text: Resources
    right:
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Code source]({{< meta var.url-repo >}}){.external target="_blank"}

execute:
  freeze: auto  # re-render only when source changes

format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
