
project:
  type: website

website:
  title: "Quarto tuto"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: Home
      - href: doc/creer-site.qmd
        text: Créer son site
      - text: Cours
        menu:
          - href: doc/cours/cm1.qmd
            text: "Cours n°1"
      - text: Slides
        menu:
          - href: doc/slide/slide1.qmd
            text: "Slides n°1"
          - href: doc/slide/codeR.qmd
            text: "Code R"
          - href: doc/slide/codePython.qmd
            text: "Code Python"
      - text: TP
        menu:
          - href: doc/tp/tp1.qmd
            text: "TP n°1"
    right:
      - icon: github
        href: https://github.com/ludo2ne/quarto-tuto
        target: "_blank"
  page-footer:
    right: |
      Website built with <a href=https://quarto.org/ target="_blank">Quarto</a><br>
      <a href=https://github.com/ludo2ne/quarto-tuto target="_blank">Source code</a>
  repo-url: https://github.com/ludo2ne/quarto-tuto
  repo-branch: main
  reader-mode: true

format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
