---
title: "Quarto-tuto"
description: "Discover some of Quarto's features"
author: "Ludovic Deneuville"
format: html
from: markdown+emoji
---


## In a nutshell

[Quarto](https://quarto.org/){target="_blank"} is a robust, open-source tool designed for effortlessly crafting scientific reports using Markdown syntax.

- Seamlessly integrate code snippets and results from various languages such as R, Python, Julia, and more into your reports.
- Quarto offers versatile rendering options, producing outputs in multiple formats including HTML, PDF, doc, tex, Reveal.js...

It's developed by [Posit](https://posit.co/){target="_blank"}, the same team behind RStudio.

## Create a Quarto project

See section [Getting started](doc/getting-started.qmd) to create a Quarto project in a few minutes.


## Examples

You will find examples of the numerous features:

- [Web page](doc/examples/lesson.qmd)
- [Notebook](doc/examples/notebook.qmd)
- [Presentation](doc/examples/presentation.qmd)


You can use a wide range of tools:

- Tables, Lists
- Images, Videos
- Python or R code
- Mathematical formulas
- [Diagrams](https://quarto.org/docs/authoring/diagrams.html)


### Static Web pages

Quarto will beautifully format your code into HTML pages. Afterward, you can easily publish your site on GitHub, Quarto-hub, Netlify...


### Presentation

You can create presentation using [revealJS](https://quarto.org/docs/presentations/revealjs/){target="_blank"}

- Speaker view
- chalkboard
- print-pdf


### Python Notebooks

- Write it with markdown syntax
- Display it on your website
- Download *.ipynb* file and load it on Jupyter



