---
title: "Tuto Quarto-Reveal.js"
subtitle: "Create a slideshow using Quarto and Reveal.js"
author: "Ludovic Deneuville"
format:
  revealjs:
    theme: moon
    footer: "[Quarto-tuto](../../index.html)"
    slide-number: c/t                   # collapsed/total
    preview-links: true
    chalkboard: true
    controls: true
    transition: slide
from: markdown+emoji
---

## Introduction

- hello
- welcome
- [Reveal.js](https://quarto.org/docs/presentations/revealjs/)


## :dart: Objectives

- [ ] Create a slideshow
- [ ] Use the Speaker View (shortcut : S)
- [ ] Explain some metadata


## Metadata

The metadata of the current document is shown at the top of the page

- `preview-links: true` : view in current window. [Try it](https://quarto.org/docs/presentations/revealjs/)
- `transition: slide` : choose transmition mode
- `chalkboard: true` : activate chalkboard
- `controls: true` : show navigation arrows


## Speaker View

- `::: {.notes}` to add personal notes
- `S` to activate `Speaker View`

Utilisation :

- On your own screen: display Speaker View
- On the presentation screen: display the slideshow

::: {.notes}
Personal notes

- note 1
- note 2
:::


## Chalkboard

* `B` to open a blackboard
* `C` to draw on your slide


## Lists

- item 1
  - item 1.1
  - item 1.2
- item 2

incrémental display

::: incremental
- item 3
- item 4
:::


## Table

| Number | Name                    | Main City          |
| ------ | ----------------------- | ------------------ |
| 01     | Ain                     | Bourg-en-Bresse    |
| 02     | Aisne                   | Laon               |
| 03     | Allier                  | Moulins            |
| 04     | Alpes-de-Haute-Provence | Digne-les-Bains    |
| 05     | Hautes-Alpes            | Gap                |
