---
title: "Lesson 1"
description: "Some examples of use cases"
author: "Ludovic Deneuville"
format:
  html:
    toc: true
    toc-location: left
    toc-expand: 3
  pdf: default
from: markdown+emoji
number-sections: true
---

## Introduction {.unnumbered}

Welcome to this course


### Objectives {.unnumbered}

- [ ] Create a webpage
- [ ] Learn how to use metadata
- [ ] Add a link in the navigation bar
- [ ] Writing in markdown


## Metadata

This file's metadata is displayed at the top between the "---".

### Basic setup

```yaml
title: "Title of this page"
description: "Description of this page"
author: "Author name"
format: html                             # because it's a webpage
from: markdown+emoji                     # you use markdown language
```

### Advanced

#### Add a table of contents

With the following setup, all titles, i.e. lines beginning with `#` will be added to the table of contents.

```yaml
format:
  html:
    toc: true                            # Add a Table Of Contents
    toc-location: left
    toc-expand: 3                        # 1 : only main titles ... 5 : highly detailed
```

If you want to remove a title from the table of contents, use the `unlisted` class :

```
# My title {.unlisted}
```

### Self-numbering

If you use this setup `number-sections: true`, each title will be numbered.  
If you don't want to number a part, use class `unnumbered` :

```
# Introduction {.unnumbered}
```


### Export pdf

The format of a web page is html.  
But you can also export in pdf format.

```yaml
format:
  html:
    ...
  pdf: default
```

When you will render the quarto project, it will create a file `lesson.pdf` in addition of `lesson.html`.  
On the webpage, a link will appear under the table of contents to download the pdf.

:::::: {.callout-note}
To perform this you have to install first tinytex : `quarto install tinytex`
:::


## Add a link in the navigation bar

The navigation bar is setup in the file `_quarto.yml`.
Look for `navbar` key, and then add a link to this page



## Markdown tips

### Unordered List

```
- first
- second
- third
- [ ] checkbox
```



## Quarto tips


### Tabulations

::: {.panel-tabset}

#### Code

``` {.python filename="file.py"}
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
pairs = np.random.rand(10, 2)

plt.scatter(pairs[:, 0], pairs[:, 1], color='blue', alpha=0.7)
plt.show()
```

#### Plot

``` {python}
#| code-fold: true
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
pairs = np.random.rand(10, 2)

plt.scatter(pairs[:, 0], pairs[:, 1], color='blue', alpha=0.7)
plt.show()
```

#### Data

``` {python filename="file.py"}
#| code-fold: true
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
pairs = np.random.rand(10, 2)
print(pairs)
```

:::



### Code

```{python}

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

x = np.linspace(-5, 5, 1000)

pdf = norm.pdf(x, 0, 1)
plt.plot(x, pdf, label='Normal Distribution')
plt.show()
```


### Callout Blocks

:::{.callout-note}
Note that there are five types of callouts, including:
`note`, `tip`, `warning`, `caution`, and `important`.
:::


::: {.callout-tip collapse="true"}
## Show

Hidden text
:::
