---
title: "Code Python dans les slides"
author: "Ludovic Deneuville"
format:
  html:
    toc: true
    toc-location: left
    toc-expand: 3 
    code-tools:
      source: true
      toggle: false
from: markdown+emoji
number-sections: true
lightbox: true
---


## Python

If you want to run python code in your quarto document, first you will have to :

- [ ] Download and install [Python](https://www.python.org/downloads/){target="_blank"}
- [ ] Install jupyter
  - `pip install jupyter`
- [ ] Install all needed packages
  - `pip install matplotlib numpy pandas ...`

::: {.callout-tip}
Instead of install packages one by one

- list all needed packages in file `requirements.txt` at the project root
- run `pip install -r requirements.txt`
:::


Official documentation :

- [Using Python](https://quarto.org/docs/computations/python.html){target="_blank"}
- [Jupyter Code Cells](https://quarto.org/docs/reference/cells/cells-jupyter.html){target="_blank"}

## Cells

### How it works ?

On the left side, you can see the code entered in the *.qmd* file, and on the right side, you can see the result.

:::: {.columns}
::: {.column}
Code in your *.qmd* file

```{{python}}
1+1
```
:::

::: {.column}
Output

```{python}
1+1
```
:::
::::

### Cell options

Cell options impact the execution and output of executable code blocks.  
They are specified within comments at the beginning of a block.

Some option examples :

```{{python}}
#| label: my_label         # Unique label for code cell
#| eval: true              # Evaluate the cell
#| echo: true              # Print the code
#| output: false           # Don't print the output
a = [1, 2, 3, 4]
print(a)
```


### Imports

To facilitate import management, it is recommended to group all of them in the first cell.

```{python}
#| label: python-imports
import numpy as np
import matplotlib.pyplot as plt

from scipy.stats import norm
from IPython.display import Markdown
from tabulate import tabulate

```

### A non-evaluated cell

If you add a dot (.) before the keyword `python`, the cell will **not** be evaluated.

:::: {.columns}
::: {.column}
Code

```
```{.python}
x = np.linspace(-5, 5, 1000)

pdf = norm.pdf(x, 0, 1)
plt.plot(x, pdf, label='Normal Distribution')
plt.show()
```
:::

::: {.column}
Output

```{.python}
x = np.linspace(-3, 3, 1000)

pdf = norm.pdf(x, 0, 1)
plt.plot(x, pdf, label='Normal Distribution')
plt.show()
```
:::
::::


### An evaluated cell

if you remove the dot (.) before the keyword `Python`, the cell will be evaluated.


```{python}
x = np.linspace(-3, 3, 1000)

pdf = norm.pdf(x, 0, 1)
plt.plot(x, pdf, label='Normal Distribution')
plt.show()
```


## Tabulations

::: {.panel-tabset}

#### Code

``` {python}
#| filename: file.py
#| eval: false
np.random.seed(42)
pairs = np.random.rand(10, 2)

plt.scatter(pairs[:, 0], pairs[:, 1], color='blue', alpha=0.7)
plt.show()
```

#### Plot

```{python}
#| code-fold: true
np.random.seed(42)
pairs = np.random.rand(10, 2)

plt.scatter(pairs[:, 0], pairs[:, 1], color='blue', alpha=0.7)
plt.show()
```

#### Data

Display table of data using `tabulate` ([see imports](#python-imports))

``` {python}
#| code-fold: true

np.random.seed(42)
pairs = np.random.rand(10, 2)

Markdown(tabulate(
  pairs, 
  headers=["X","Y"]
))
```

:::






## Line numbers

```{python}
#| code-line-numbers: true
def fibonacci(n) -> list[int]:
    """Generate the Fibonacci sequence up to the nth term."""
    if not isinstance(n, int):
        raise TypeError("n must be an integer")

    fib_sequence = []
    a, b = 0, 1
    for _ in range(n):
        fib_sequence.append(a)
        a, b = b, a + b
    return fib_sequence

# Example usage
print(fibonacci(10))
```


### Inline code


It is possible to embed code within a line of text : 

- The mean of fibonacci(10) is `{python} np.mean(fibonacci(10))`.



## A classer

```{python}
#| label: fig-collatz27
#| fig-cap: "Collatz conjecture starting with n = 27"
def collatz_conjecture(n):
    sequence = [n]
    
    while n != 1:
        if n % 2 == 0:
            n = n // 2
        else:
            n = 3 * n + 1
        sequence.append(n)
    
    return sequence

def plot_collatz(n):
    sequence = collatz_conjecture(n)
    plt.plot(sequence, linestyle='-', marker='o', markersize=3, color='darkcyan')
    plt.xlabel('Step')
    plt.ylabel('Value')
    plt.title('Collatz conjecture')
    plt.grid(True)
    plt.show()

plot_collatz(27)
```


Reference to the [figure](#fig-collatz27)