---
title: "Tuto Quarto-revealJS"
subtitle: "Create beautiful interactive slide with Reveal.js"
author: "Ludovic Deneuville"
format:
  revealjs:
    theme: moon
    footer: "[Quarto-tuto](../../index.html)"
    slide-number: c/t                   # collapsed/total
    preview-links: true
    chalkboard: true
    controls: true
    transition: slide
    code-tools: true
resources:
  - demo.pdf
---


## Code R dans les slides

[Utiliser R](https://quarto.org/docs/computations/r.html){.external target="_blank"}


## installer R et les packages

- https://cloud.r-project.org/
- install.packages("rmarkdown")
- install.packages("ggplot2")


## Executable Code

```{r}
#| echo: true
#| fig-width: 10
#| fig-height: 4.5
library(ggplot2)
ggplot(mtcars, aes(hp, mpg, color = am)) +
  geom_point() +
  geom_smooth(formula = y ~ x, method = "loess")
```

## Tabsets {.smaller .scrollable transition="slide"}

::: panel-tabset
### Plot

```{r}
library(ggplot2)
ggplot(mtcars, aes(hp, mpg, color = am)) +
  geom_point() +
  geom_smooth(formula = y ~ x, method = "loess")
```

### Data

```{r}
knitr::kable(mtcars)
```
:::



@fig-airquality Température et niveau d'ozone.

```{r}
#| echo: false
#| output: true
#| label: fig-airquality
#| fig-cap: Température et niveau d'ozone.
#| warning: false

ggplot(airquality, aes(Temp, Ozone)) + 
  geom_point() + 
  geom_smooth(method = "loess")
```

### Code block and inline code

```{r}
a <- c(1, 2, 3, 4)
```

la moyenne de a est de `r mean(a)`.